#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
#
# T-2.7 — golden clock card.
#
# Renders the ClockWidget's card with the *same* Pillow calls and the *same*
# .pil fonts the Python uses, then quantises the RGB888 result down to the
# RGB565 that the HUB75 panel actually receives. Emits:
#   * test/test_native/golden_clock.h  — the RGB565 grid the C test diffs against
#   * test/out/golden_clock.png        — eyeball reference (565 expanded to 888)
#
# The parity domain is RGB565: firmware renders RGB565, this renders RGB888 and
# quantises identically (r>>3, g>>2, b>>3). The C test compares the uint16
# grids element-for-element — glyph shape and position must be byte-identical.

from __future__ import annotations

import datetime
import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

REPO = Path(__file__).resolve().parent.parent
MARQUEE_FONTS = Path("/home/anthony/VSCode/Marquee/marquee/matrix/fonts")
OUT_HEADER = REPO / "test" / "test_native" / "golden_clock.h"
OUT_PNG = REPO / "test" / "out" / "golden_clock.png"

CARD_W = 64
PANEL_H = 32
TIME_COLOR = (255, 255, 255)
DATE_COLOR = (140, 140, 140)

# A fixed time that exercises digits, ':', ' ', AM/PM letters and lowercase date.
NOW = datetime.datetime(2025, 12, 25, 15, 30)  # 3:30 PM, Wed 12/25


def q565(rgb):
    r, g, b = rgb
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def main() -> int:
    if not MARQUEE_FONTS.exists():
        print(f"missing {MARQUEE_FONTS}", file=sys.stderr)
        return 1

    font_time = ImageFont.load(str(MARQUEE_FONTS / "spleen-6x12.pil"))
    font_date = ImageFont.load(str(MARQUEE_FONTS / "spleen-5x8.pil"))

    # --- verbatim from ClockWidget.cards() ---
    card = Image.new("RGB", (CARD_W, PANEL_H), (0, 0, 0))
    draw = ImageDraw.Draw(card)
    time_str = f"{NOW.hour % 12 or 12}:{NOW.minute:02d} " + ("AM" if NOW.hour < 12 else "PM")
    date_str = NOW.strftime("%a %m/%d")

    tw = draw.textlength(time_str, font=font_time)
    tx = max(0, int((CARD_W - tw) / 2))
    draw.text((tx, 2), time_str, font=font_time, fill=TIME_COLOR)

    dw = draw.textlength(date_str, font=font_date)
    dx = max(0, int((CARD_W - dw) / 2))
    draw.text((dx, 22), date_str, font=font_date, fill=DATE_COLOR)
    # --- end verbatim ---

    px = card.load()
    grid = [q565(px[x, y]) for y in range(PANEL_H) for x in range(CARD_W)]

    OUT_HEADER.parent.mkdir(parents=True, exist_ok=True)
    rows = []
    for y in range(PANEL_H):
        cells = ", ".join(f"0x{grid[y * CARD_W + x]:04X}" for x in range(CARD_W))
        rows.append(f"    {cells},")
    OUT_HEADER.write_text(
        "// SPDX-License-Identifier: GPL-3.0-only\n"
        "//\n"
        "// GENERATED by tools/gen_parity_golden.py — golden clock card (T-2.7).\n"
        f"// RGB565 grid {CARD_W}x{PANEL_H}; time '{time_str}'  date '{date_str}'.\n"
        "#pragma once\n"
        "#include <cstdint>\n"
        "inline constexpr int GOLDEN_W = 64, GOLDEN_H = 32;\n"
        "inline constexpr uint16_t GOLDEN_CLOCK[64 * 32] = {\n"
        + "\n".join(rows)
        + "\n};\n"
    )

    # PNG: expand 565 back to 888 with bit-replication for eyeballing.
    img = Image.new("RGB", (CARD_W, PANEL_H))
    ip = img.load()
    for y in range(PANEL_H):
        for x in range(CARD_W):
            v = grid[y * CARD_W + x]
            r5 = (v >> 11) & 31
            g6 = (v >> 5) & 63
            b5 = v & 31
            ip[x, y] = ((r5 << 3) | (r5 >> 2), (g6 << 2) | (g6 >> 4), (b5 << 3) | (b5 >> 2))
    OUT_PNG.parent.mkdir(parents=True, exist_ok=True)
    img.save(OUT_PNG)
    print(f"golden_clock.h ({CARD_W}x{PANEL_H}) + PNG written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
