#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
#
# T-6.3 — golden PRE game card.
#
# Reproduces game_strip._render_card_pre for the no-logo fallback path directly
# with Pillow so this test does not import Marquee's driver module. The C++
# test diffs the RGB565 grid produced by render_game_card_pre against it.

from __future__ import annotations

import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

REPO = Path(__file__).resolve().parent.parent
MARQUEE = Path("/home/anthony/VSCode/Marquee")
OUT_HEADER = REPO / "test" / "test_native" / "golden_game_pre.h"
OUT_PNG = REPO / "test" / "out" / "golden_game_pre.png"

CARD_W = 64
PANEL_H = 32
LOGO_H = 24
WHITE = (255, 255, 255)
DIM = (110, 110, 110)
AWAY = ("KC", "e4393c")
HOME = ("LAR", "22a7de")
TIME_STR = "10:30"


def q565(rgb):
    r, g, b = rgb
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def hex_to_rgb(color: str):
    c = color.lstrip("#").zfill(6)
    return (int(c[0:2], 16), int(c[2:4], 16), int(c[4:6], 16))


def main() -> int:
    fonts = MARQUEE / "marquee/matrix/fonts"
    if not fonts.exists():
        print(f"missing {fonts}", file=sys.stderr)
        return 1

    font = ImageFont.load(str(fonts / "spleen-5x8.pil"))
    card = Image.new("RGB", (CARD_W, PANEL_H), (0, 0, 0))
    draw = ImageDraw.Draw(card)

    for abbr, color, align in ((AWAY[0], AWAY[1], "left"), (HOME[0], HOME[1], "right")):
        tw = int(draw.textlength(abbr, font=font)) + 1
        x = 0 if align == "left" else CARD_W - tw
        y = 1 + max(0, (LOGO_H - 8) // 2)
        draw.text((x, y), abbr, font=font, fill=hex_to_rgb(color))

    vs_w = int(draw.textlength("VS", font=font))
    draw.text(((CARD_W - vs_w) // 2, 14), "VS", font=font, fill=WHITE)

    ts_w = int(draw.textlength(TIME_STR, font=font))
    draw.text(((CARD_W - ts_w) // 2, 25), TIME_STR, font=font, fill=DIM)

    px = card.load()
    grid = [q565(px[x, y]) for y in range(PANEL_H) for x in range(CARD_W)]

    OUT_HEADER.parent.mkdir(parents=True, exist_ok=True)
    rows = []
    for y in range(PANEL_H):
        cells = ", ".join(f"0x{grid[y * CARD_W + x]:04X}" for x in range(CARD_W))
        rows.append(f"    {cells},")
    OUT_HEADER.write_text(
        "// SPDX-License-Identifier: GPL-3.0-only\n"
        "//\n"
        "// GENERATED by tools/gen_game_pre_golden.py — golden PRE card (T-6.3).\n"
        f"// RGB565 grid {CARD_W}x{PANEL_H}; fallback '{AWAY[0]}' vs '{HOME[0]}' at {TIME_STR}.\n"
        "#pragma once\n"
        "#include <cstdint>\n"
        "inline constexpr int GOLDEN_GAME_PRE_W = 64, GOLDEN_GAME_PRE_H = 32;\n"
        "inline constexpr uint16_t GOLDEN_GAME_PRE[64 * 32] = {\n"
        + "\n".join(rows)
        + "\n};\n"
    )

    img = Image.new("RGB", (CARD_W, PANEL_H))
    ip = img.load()
    for y in range(PANEL_H):
        for x in range(CARD_W):
            v = grid[y * CARD_W + x]
            r5 = (v >> 11) & 31
            g6 = (v >> 5) & 63
            b5 = v & 31
            ip[x, y] = ((r5 << 3) | (r5 >> 2), (g6 << 2) | (g6 >> 4), (b5 << 3) | (b5 >> 2))
    OUT_PNG.parent.mkdir(parents=True, exist_ok=True)
    img.save(OUT_PNG)
    print(f"golden_game_pre.h ({CARD_W}x{PANEL_H}) + PNG written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
