#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
#
# T-6.4 — golden FINAL game cards.
#
# Reproduces game_strip._render_card_post for the no-logo fallback path with
# Pillow. The C++ test diffs render_game_card_post against the RGB565 grids.

from __future__ import annotations

import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

REPO = Path(__file__).resolve().parent.parent
MARQUEE = Path("/home/anthony/VSCode/Marquee")
OUT_HEADER = REPO / "test" / "test_native" / "golden_game_post.h"
OUT_PNG = REPO / "test" / "out" / "golden_game_post.png"
OUT_PNG_PREV = REPO / "test" / "out" / "golden_game_post_prev.png"

CARD_W = 64
PANEL_H = 32
LOGO_H = 19
WHITE = (255, 255, 255)
DIM = (110, 110, 110)
AWAY = ("KC", "e4393c")
HOME = ("LAR", "22a7de")
SCORE = "3-2"
STATUS = "FINAL"
STATUS_PREV = "12/24"


def q565(rgb):
    r, g, b = rgb
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def hex_to_rgb(color: str):
    c = color.lstrip("#").zfill(6)
    return (int(c[0:2], 16), int(c[2:4], 16), int(c[4:6], 16))


def draw_card(small_font, score_font, status: str):
    card = Image.new("RGB", (CARD_W, PANEL_H), (0, 0, 0))
    draw = ImageDraw.Draw(card)

    for abbr, color, align in ((AWAY[0], AWAY[1], "left"), (HOME[0], HOME[1], "right")):
        tw = int(draw.textlength(abbr, font=small_font)) + 1
        x = 0 if align == "left" else CARD_W - tw
        y = 1 + max(0, (LOGO_H - 8) // 2)
        draw.text((x, y), abbr, font=small_font, fill=hex_to_rgb(color))

    sw = int(draw.textlength(SCORE, font=score_font))
    draw.text(((CARD_W - sw) // 2, 11), SCORE, font=score_font, fill=WHITE)

    fw = int(draw.textlength(status, font=small_font))
    draw.text(((CARD_W - fw) // 2, 22), status, font=small_font, fill=DIM)
    return card


def grid_for(card):
    px = card.load()
    return [q565(px[x, y]) for y in range(PANEL_H) for x in range(CARD_W)]


def array_text(name, grid):
    rows = []
    for y in range(PANEL_H):
        cells = ", ".join(f"0x{grid[y * CARD_W + x]:04X}" for x in range(CARD_W))
        rows.append(f"    {cells},")
    return f"inline constexpr uint16_t {name}[{CARD_W * PANEL_H}] = {{\n" + "\n".join(rows) + "\n};\n"


def save_png(path, grid):
    img = Image.new("RGB", (CARD_W, PANEL_H))
    ip = img.load()
    for y in range(PANEL_H):
        for x in range(CARD_W):
            v = grid[y * CARD_W + x]
            r5 = (v >> 11) & 31
            g6 = (v >> 5) & 63
            b5 = v & 31
            ip[x, y] = ((r5 << 3) | (r5 >> 2), (g6 << 2) | (g6 >> 4), (b5 << 3) | (b5 >> 2))
    img.save(path)


def main() -> int:
    fonts = MARQUEE / "marquee/matrix/fonts"
    if not fonts.exists():
        print(f"missing {fonts}", file=sys.stderr)
        return 1

    small = ImageFont.load(str(fonts / "spleen-5x8.pil"))
    score = ImageFont.load(str(fonts / "spleen-6x12.pil"))

    grid = grid_for(draw_card(small, score, STATUS))
    grid_prev = grid_for(draw_card(small, score, STATUS_PREV))

    OUT_HEADER.parent.mkdir(parents=True, exist_ok=True)
    OUT_PNG.parent.mkdir(parents=True, exist_ok=True)
    OUT_HEADER.write_text(
        "// SPDX-License-Identifier: GPL-3.0-only\n"
        "//\n"
        "// GENERATED by tools/gen_game_post_golden.py — golden FINAL cards (T-6.4).\n"
        f"// RGB565 grids {CARD_W}x{PANEL_H}; fallback '{AWAY[0]}' vs '{HOME[0]}', score {SCORE}.\n"
        "#pragma once\n"
        "#include <cstdint>\n"
        "inline constexpr int GOLDEN_GAME_POST_W = 64, GOLDEN_GAME_POST_H = 32;\n"
        + array_text("GOLDEN_GAME_POST", grid)
        + array_text("GOLDEN_GAME_POST_PREV", grid_prev)
    )

    save_png(OUT_PNG, grid)
    save_png(OUT_PNG_PREV, grid_prev)
    print(f"golden_game_post.h ({CARD_W}x{PANEL_H}) + PNGs written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
