#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
#
# T-10.2 — golden weather card (fresh design; Marquee's widget was a stub).
# Mirrors lib/render/weather_widget.h exactly: 12-glyph cond truncation,
# 6x12 digits + Pillow 5x5 outline ring (the primitives.cpp proven case)
# + 5x8 unit, gray high/low line.

from __future__ import annotations

import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

REPO = Path(__file__).resolve().parent.parent
MARQUEE = Path("/home/anthony/VSCode/Marquee")
OUT_HEADER = REPO / "test" / "test_native" / "golden_weather.h"
OUT_PNG = REPO / "test" / "out" / "golden_weather.png"

CARD_W, PANEL_H = 64, 32
COND, TEMP, HI, LO, UNIT = "Partly cloudy", 72, 75, 66, "F"
WHITE, GRAY = (255, 255, 255), (140, 140, 140)


def q565(rgb):
    r, g, b = rgb
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def main() -> int:
    fonts = MARQUEE / "marquee/matrix/fonts"
    if not fonts.exists():
        print(f"missing {fonts}", file=sys.stderr)
        return 1
    small = ImageFont.load(str(fonts / "spleen-5x8.pil"))
    big = ImageFont.load(str(fonts / "spleen-6x12.pil"))

    card = Image.new("RGB", (CARD_W, PANEL_H), (0, 0, 0))
    draw = ImageDraw.Draw(card)

    cond = COND[:12]
    draw.text(((CARD_W - len(cond) * 5) // 2, 1), cond, font=small, fill=WHITE)

    tbuf, ubuf = str(TEMP), UNIT
    dw = len(tbuf) * 6
    x0 = (CARD_W - (dw + 2 + 5 + 2 + 5)) // 2
    draw.text((x0, 9), tbuf, font=big, fill=WHITE)
    cx = x0 + dw + 4
    draw.ellipse([cx - 2, 12 - 2, cx + 2, 12 + 2], outline=WHITE)
    draw.text((x0 + dw + 9, 13), ubuf, font=small, fill=WHITE)

    hl = f"H {HI}  L {LO}"
    draw.text(((CARD_W - len(hl) * 5) // 2, 24), hl, font=small, fill=GRAY)

    px = card.load()
    grid = [q565(px[x, y]) for y in range(PANEL_H) for x in range(CARD_W)]

    OUT_HEADER.parent.mkdir(parents=True, exist_ok=True)
    OUT_PNG.parent.mkdir(parents=True, exist_ok=True)
    rows = [", ".join(f"0x{grid[y * CARD_W + x]:04X}" for x in range(CARD_W))
            for y in range(PANEL_H)]
    rows = [f"    {r}," for r in rows]

    OUT_HEADER.write_text(
        "// SPDX-License-Identifier: GPL-3.0-only\n"
        "//\n"
        "// GENERATED by tools/gen_weather_golden.py — golden weather card (T-10.2).\n"
        f"// RGB565 grid {CARD_W}x{PANEL_H}; '{COND}' {TEMP}{UNIT} H{HI} L{LO}.\n"
        "#pragma once\n"
        "#include <cstdint>\n"
        "inline constexpr int GOLDEN_WEATHER_W = 64, GOLDEN_WEATHER_H = 32;\n"
        "inline constexpr uint16_t GOLDEN_WEATHER[64 * 32] = {\n"
        + "\n".join(rows)
        + "\n};\n"
    )

    img = Image.new("RGB", (CARD_W, PANEL_H))
    ip = img.load()
    for y in range(PANEL_H):
        for x in range(CARD_W):
            v = grid[y * CARD_W + x]
            r5, g6, b5 = (v >> 11) & 31, (v >> 5) & 63, v & 31
            ip[x, y] = ((r5 << 3) | (r5 >> 2), (g6 << 2) | (g6 >> 4), (b5 << 3) | (b5 >> 2))
    img.save(OUT_PNG)
    print(f"golden_weather.h ({CARD_W}x{PANEL_H}) + PNG written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
