#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
#
# T-3.5/T-3.6 — golden logo parity.
#
# Reads the REAL atlas (logos.bin) and emits test/test_native/golden_logo.h:
#   input:   one logo's atlas bytes verbatim — RGB565 px + 1-bit mask, the
#            exact octets the firmware blits out of flash.
#   A) golden canvas of the Python's masked paste, card.paste(logo,(x,y),
#      mask=logo), fed that same art upscaled 565->888 (bit-replicated, so
#      re-quantising is the identity). Atlas alpha is binary by construction
#      (threshold 128 at build), so Pillow's blend degenerates to exactly the
#      alpha test blit_logo implements — that is the equivalence under test.
#   B) golden canvas of the T-3.6 fallback: abbreviation[:3] in team colour,
#      spleen-5x8, text_y = y + (logo_h - 8) // 2 (game_strip._paste_logo).
# The hard gate is the C test diffing RGB565 grids; PNGs are for eyeballs.

from __future__ import annotations

import struct
import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tools"))
import build_logos

MARQUEE_FONTS = Path("/home/anthony/VSCode/Marquee/marquee/matrix/fonts")
OUT_HEADER = REPO / "test" / "test_native" / "golden_logo.h"
OUT_PNGS = (REPO / "test" / "out" / "logo_golden_paste.png",
            REPO / "test" / "out" / "logo_golden_fallback.png")

CARD_W, PANEL_H = 64, 32
BG = (16, 32, 64)              # non-black: masked-out px must show it
LOGO_KEY = ("epl", "LIV")   # thin-stroke crest: punishes any mask off-by-one
LIVE_X, LIVE_Y = 4, 0          # LIVE-card corner slot
FB_X, FB_Y, FB_LOGO_H = 20, 0, 13
COLOR_HEX = "c8102e"           # liverly red


def q565(rgb):
    r, g, b = rgb
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def up565(v):
    r5, g6, b5 = (v >> 11) & 31, (v >> 5) & 63, v & 31
    return ((r5 << 3) | (r5 >> 2), (g6 << 2) | (g6 >> 4), (b5 << 3) | (b5 >> 2))


def main() -> int:
    atlas = (REPO / "logos.bin").read_bytes()
    table, height = build_logos.read(atlas)
    r = table[LOGO_KEY + (24,)]  # PRE-slot row: premultiplied over black, mask = alpha > 0
    w, h, blob = r["w"], r["h"], r["blob"]
    n_px = w * h
    px565 = list(struct.unpack(f"<{n_px}H", blob[:n_px * 2]))
    mask = list(blob[n_px * 2:])
    assert len(mask) == ((w + 7) // 8) * h

    # --- A) verbatim: card.paste(logo, (x, y), mask=logo), atlas art fed in.
    rgba = Image.new("RGBA", (w, h))
    stride = (w + 7) // 8
    rgba.putdata([(*up565(px565[py * w + px]),
                   255 if mask[py * stride + (px >> 3)] & (0x80 >> (px & 7)) else 0)
                  for py in range(h) for px in range(w)])
    card = Image.new("RGB", (CARD_W, PANEL_H), BG)
    card.paste(rgba, (LIVE_X, LIVE_Y), rgba)

    # --- B) verbatim: _paste_logo fallback branch -------------------------
    fb = Image.new("RGB", (CARD_W, PANEL_H), (0, 0, 0))
    font = ImageFont.load(str(MARQUEE_FONTS / "spleen-5x8.pil"))
    color = tuple(int(COLOR_HEX[i:i + 2], 16) for i in (0, 2, 4))
    ImageDraw.Draw(fb).text((FB_X, FB_Y + max(0, (FB_LOGO_H - 8) // 2)),
                           "LIV", font=font, fill=color)

    def grid(img):
        px = img.load()
        return [q565(px[x, y]) for y in range(PANEL_H) for x in range(CARD_W)]

    gold_a, gold_b = grid(card), grid(fb)
    assert any(v != q565(BG) for v in gold_a), "paste wrote nothing"
    assert any(v for v in gold_b), "fallback text wrote nothing"

    def arr(name, ctype, vals, per_line):
        lines = []
        for i in range(0, len(vals), per_line):
            cells = ", ".join(f"0x{v:02X}" if ctype == "uint8_t"
                              else f"0x{v:04X}" for v in vals[i:i + per_line])
            lines.append(f"    {cells},")
        return f"inline constexpr {ctype} {name}[] = {{\n" + "\n".join(lines) + "\n};\n"

    OUT_HEADER.write_text(
        "// SPDX-License-Identifier: GPL-3.0-only\n"
        "//\n"
        "// GENERATED by tools/gen_logo_golden.py (T-3.5/T-3.6 parity) — do not\n"
        f"// edit. Atlas logo {LOGO_KEY[0]}:{LOGO_KEY[1]} {w}x{h} (atlas h={height})\n"
        f"// pasted at ({LIVE_X},{LIVE_Y}) on bg {BG}; fallback 'LIV' {COLOR_HEX}\n"
        f"// at x={FB_X}, logo_h={FB_LOGO_H}. Regenerate with logos.bin present.\n"
        "#pragma once\n"
        "#include <cstdint>\n"
        "inline constexpr int GCARD_W = 64, GCARD_H = 32;\n"
        f"inline constexpr uint16_t GLOGO_BG = {q565(BG)};\n"
        f"inline constexpr int LOGO_X = {LIVE_X}, LOGO_Y = {LIVE_Y};\n"
        f"inline constexpr int FBX = {FB_X}, FBY = {FB_Y}, FBH = {FB_LOGO_H};\n"
        f"inline constexpr uint16_t FBCOL = {q565(color)};\n"
        f"inline constexpr int LOGO_W = {w}, LOGO_H = {h};\n"
        + arr("LOGO_PX", "uint16_t", px565, 12)
        + arr("LOGO_MASK", "uint8_t", mask, 16)
        + arr("GOLD_PASTE", "uint16_t", gold_a, 16)
        + arr("GOLD_FALLBACK", "uint16_t", gold_b, 16)
    )

    for out, vals in zip(OUT_PNGS, (gold_a, gold_b)):
        img = Image.new("RGB", (CARD_W, PANEL_H))
        ip = img.load()
        for y in range(PANEL_H):
            for x in range(CARD_W):
                ip[x, y] = up565(vals[y * CARD_W + x])
        out.parent.mkdir(parents=True, exist_ok=True)
        img.save(out)
    print(f"golden_logo.h: {LOGO_KEY} {w}x{h}, px {n_px}, mask {len(mask)} B")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
