#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
#
# T-10.4 — golden ticker card (fresh design; Marquee's ticker.py was a
# stub). Mirrors lib/render/ticker_widget.h: three centred spleen-5x8
# lines — label gray, value white, delta green/red by leading sign.

from __future__ import annotations

import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

REPO = Path(__file__).resolve().parent.parent
MARQUEE = Path("/home/anthony/VSCode/Marquee")
OUT_HEADER = REPO / "test" / "test_native" / "golden_ticker.h"
OUT_PNG = REPO / "test" / "out" / "golden_ticker.png"

CARD_W, PANEL_H = 64, 32
LABEL, VAL, DELTA = "bitcoin", "$81,268", "+1.1%"
WHITE, GRAY, GREEN = (255, 255, 255), (140, 140, 140), (60, 210, 60)


def q565(rgb):
    r, g, b = rgb
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def main() -> int:
    fonts = MARQUEE / "marquee/matrix/fonts"
    if not fonts.exists():
        print(f"missing {fonts}", file=sys.stderr)
        return 1
    small = ImageFont.load(str(fonts / "spleen-5x8.pil"))

    card = Image.new("RGB", (CARD_W, PANEL_H), (0, 0, 0))
    draw = ImageDraw.Draw(card)
    for text, col, y in ((LABEL, GRAY, 1), (VAL, WHITE, 12), (DELTA, GREEN, 22)):
        if text:
            draw.text(((CARD_W - len(text) * 5) // 2, y), text, font=small, fill=col)

    px = card.load()
    grid = [q565(px[x, y]) for y in range(PANEL_H) for x in range(CARD_W)]

    OUT_HEADER.parent.mkdir(parents=True, exist_ok=True)
    OUT_PNG.parent.mkdir(parents=True, exist_ok=True)
    rows = [", ".join(f"0x{grid[y * CARD_W + x]:04X}" for x in range(CARD_W))
            for y in range(PANEL_H)]
    rows = [f"    {r}," for r in rows]

    OUT_HEADER.write_text(
        "// SPDX-License-Identifier: GPL-3.0-only\n"
        "//\n"
        "// GENERATED by tools/gen_ticker_golden.py — golden ticker card (T-10.4).\n"
        f"// RGB565 grid {CARD_W}x{PANEL_H}; '{LABEL}' '{VAL}' '{DELTA}'.\n"
        "#pragma once\n"
        "#include <cstdint>\n"
        "inline constexpr int GOLDEN_TICKER_W = 64, GOLDEN_TICKER_H = 32;\n"
        "inline constexpr uint16_t GOLDEN_TICKER[64 * 32] = {\n"
        + "\n".join(rows)
        + "\n};\n"
    )

    img = Image.new("RGB", (CARD_W, PANEL_H))
    ip = img.load()
    for y in range(PANEL_H):
        for x in range(CARD_W):
            v = grid[y * CARD_W + x]
            r5, g6, b5 = (v >> 11) & 31, (v >> 5) & 63, v & 31
            ip[x, y] = ((r5 << 3) | (r5 >> 2), (g6 << 2) | (g6 >> 4), (b5 << 3) | (b5 >> 2))
    img.save(OUT_PNG)
    print(f"golden_ticker.h ({CARD_W}x{PANEL_H}) + PNG written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
