#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
#
# T-6.5 — golden generic LIVE game card.
#
# Reproduces game_strip._render_card_live for the no-logo fallback path and no
# situation graphic. The C++ test diffs render_game_card_live against it.

from __future__ import annotations

import sys
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

REPO = Path(__file__).resolve().parent.parent
MARQUEE = Path("/home/anthony/VSCode/Marquee")
OUT_HEADER = REPO / "test" / "test_native" / "golden_game_live.h"
OUT_PNG = REPO / "test" / "out" / "golden_game_live.png"

CARD_W = 64
PANEL_H = 32
LOGO_H = 13
WHITE = (255, 255, 255)
AWAY = ("KC", "e4393c", "4")
HOME = ("LAR", "22a7de", "2")


def q565(rgb):
    r, g, b = rgb
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def hex_to_rgb(color: str):
    c = color.lstrip("#").zfill(6)
    return (int(c[0:2], 16), int(c[2:4], 16), int(c[4:6], 16))


def main() -> int:
    fonts = MARQUEE / "marquee/matrix/fonts"
    if not fonts.exists():
        print(f"missing {fonts}", file=sys.stderr)
        return 1

    small = ImageFont.load(str(fonts / "spleen-5x8.pil"))
    score_font = ImageFont.load(str(fonts / "spleen-6x12.pil"))
    score_y = max(0, (LOGO_H - 12) // 2)

    card = Image.new("RGB", (CARD_W, PANEL_H), (0, 0, 0))
    draw = ImageDraw.Draw(card)

    for abbr, color, score, align in ((AWAY[0], AWAY[1], AWAY[2], "left"),
                                      (HOME[0], HOME[1], HOME[2], "right")):
        lw = int(draw.textlength(abbr, font=small)) + 1
        if align == "left":
            draw.text((0, max(0, (LOGO_H - 8) // 2)), abbr, font=small, fill=hex_to_rgb(color))
            draw.text((lw + 2, score_y), score, font=score_font, fill=WHITE)
        else:
            draw.text((CARD_W - lw, max(0, (LOGO_H - 8) // 2)), abbr, font=small,
                      fill=hex_to_rgb(color))
            sw = int(draw.textlength(score, font=score_font))
            draw.text((CARD_W - lw - 2 - sw, score_y), score, font=score_font, fill=WHITE)

    px = card.load()
    grid = [q565(px[x, y]) for y in range(PANEL_H) for x in range(CARD_W)]

    OUT_HEADER.parent.mkdir(parents=True, exist_ok=True)
    OUT_PNG.parent.mkdir(parents=True, exist_ok=True)
    rows = []
    for y in range(PANEL_H):
        cells = ", ".join(f"0x{grid[y * CARD_W + x]:04X}" for x in range(CARD_W))
        rows.append(f"    {cells},")

    OUT_HEADER.write_text(
        "// SPDX-License-Identifier: GPL-3.0-only\n"
        "//\n"
        "// GENERATED by tools/gen_game_live_golden.py — golden generic LIVE card (T-6.5).\n"
        f"// RGB565 grid {CARD_W}x{PANEL_H}; fallback '{AWAY[0]}' {AWAY[2]} at "
        f"'{HOME[0]}' {HOME[2]}.\n"
        "#pragma once\n"
        "#include <cstdint>\n"
        "inline constexpr int GOLDEN_GAME_LIVE_W = 64, GOLDEN_GAME_LIVE_H = 32;\n"
        "inline constexpr uint16_t GOLDEN_GAME_LIVE[64 * 32] = {\n"
        + "\n".join(rows)
        + "\n};\n"
    )

    img = Image.new("RGB", (CARD_W, PANEL_H))
    ip = img.load()
    for y in range(PANEL_H):
        for x in range(CARD_W):
            v = grid[y * CARD_W + x]
            r5 = (v >> 11) & 31
            g6 = (v >> 5) & 63
            b5 = v & 31
            ip[x, y] = ((r5 << 3) | (r5 >> 2), (g6 << 2) | (g6 >> 4), (b5 << 3) | (b5 >> 2))
    img.save(OUT_PNG)
    print(f"golden_game_live.h ({CARD_W}x{PANEL_H}) + PNG written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
